Repository BIT-Studio-3/group-project-25-1-the-anti-statics, pull requests merged in 2025-04, with the labels that each got.

#101 Combined Seismic and Volcanic into one Activity Page
  src/lib/Header.svelte
  src/routes/seismic_reports_page/+page.js
  src/routes/seismic_reports_page/+page.svelte
  src/routes/volcanic_activity_page/+page.js
  src/routes/volcanic_activity_page/+page.svelte
Labels: Ready for Review

#103 Api damage
  src/lib/Header.svelte
  src/lib/damageCard.svelte
  src/routes/damage_record_page/+page.js
  src/routes/damage_record_page/+page.svelte
  src/routes/damage_record_page/post-functions/postDamage.js
Labels: Frontend

#118 SPRINT 3
  Attendance Tracker.xlsx
  Coding Standards.md
  package-lock.json
  package.json
  src/lib/Header.svelte
  src/lib/Images/dma.png
  src/lib/damageCard.svelte
  src/lib/hazardCard.svelte
  src/routes/+layout.svelte
  src/routes/+page.js
  src/routes/+page.svelte
  src/routes/Resources_Availability_Form/+page.svelte
  src/routes/Resources_Availability_Form/post-functions/postResource.js
  src/routes/alert_system/+page.svelte
  src/routes/alert_system/post-functions/postAlert.js
  src/routes/damage_record_page/+page.js
  src/routes/damage_record_page/+page.svelte
  src/routes/damage_record_page/post-functions/postDamage.js
  src/routes/hazard_page/+page.js
  src/routes/hazard_page/+page.svelte
  src/routes/hazard_page/post-function/postHazard.js
  src/routes/login/+page.svelte
  src/routes/login/utils/postLogins.js
  src/routes/road_conditions_page/+page.svelte
  src/routes/seismic_reports_page/+page.js
  src/routes/seismic_reports_page/+page.svelte
  src/routes/volcanic_activity_page/+page.js
  src/routes/volcanic_activity_page/+page.svelte
  src/stores/login.js
  src/stores/user.js
Labels: Sprint

#151 SPRINT 4
  src/app.css
  src/lib/Footer.svelte
  src/lib/GIFs/loading.gif
  src/lib/Header.svelte
  src/lib/Images/background.png
  src/lib/agencySelect.svelte
  src/lib/damageCard.svelte
  src/lib/formLayout.svelte
  src/lib/hazardCard.svelte
  src/routes/+layout.svelte
  src/routes/+page.js
  src/routes/+page.svelte
  src/routes/Resources_Availability_Form/+page.svelte
  src/routes/Resources_Availability_Form/post-functions/postResource.js
  src/routes/alert_system/+page.svelte
  src/routes/alert_system/post-functions/postAlert.js
  src/routes/damage_record_page/+page.js
  src/routes/damage_record_page/+page.svelte
  src/routes/damage_record_page/post-functions/postDamage.js
  src/routes/hazard_page/+page.js
  src/routes/hazard_page/+page.svelte
  src/routes/hazard_page/post-function/postHazard.js
  src/routes/login/+page.svelte
  src/routes/login/utils/postLogins.js
  src/stores/login.js
  src/url/url.js
Labels: Sprint
