Repository BIT-Studio-3/group-project-25-1-the-anti-statics, pull requests merged in 2025-03, with the labels that each got.

#27 Created spreadsheet to track team members attendance at standup meetings
  Attendance Tracker.xlsx
Labels: Ready for Review

#29 Maptest
  package-lock.json
  package.json
  src/lib/Map.svelte
  src/routes/+page.svelte
Labels: Ready for Review

#23 Update Team and Coding Standards
  Coding Standards.md
  Team Standards.md
  Team Standards.txt
  test.txt
Labels: Ready for Review

#33 feat(javascript): add a new feature which can help organisations conn…
  src/lib/Header.svelte
  src/routes/Resources_Availability_Form/+page.svelte
Labels: Ready for Review

#21 Updated website header to group header
  src/lib/Header.svelte
Labels: Ready for Review

#26 Add agency-specific view for data on website
  src/lib/Header.svelte
  src/lib/agencySelect.svelte
  src/lib/stores.js
  src/routes/+page.svelte
  src/routes/weather_reports_page/+page.js
  src/routes/weather_reports_page/+page.svelte
Labels: Ready for Review

#34 Alert page
  src/routes/alert_system/+page.js
  src/routes/alert_system/+page.svelte
Labels: Ready for Review

#64 Pin map
  Attendance Tracker.xlsx
  package-lock.json
  package.json
  questions.txt
  src/lib/Map.svelte
Labels: Frontend

#75 gave a simple color theme
  src/app.css
  src/lib/Footer.svelte
  src/lib/Header.svelte
  src/routes/+page.svelte
  src/routes/alert_system/+page.svelte
  src/routes/fire_and_emergency_page/+page.svelte
  src/routes/rss/+page.svelte
  src/routes/seismic_reports_page/+page.svelte
Labels: Frontend

#65 Moved MetService RSS to weather reports page
  src/routes/rss/+page.svelte
  src/routes/weather_reports_page/+page.svelte
Labels: Frontend

#85 Sprint 2
  README.md
  package-lock.json
  package.json
  src/app.css
  src/lib/Footer.svelte
  src/lib/Header.svelte
  src/lib/Map.svelte
  src/lib/agencySelect.svelte
  src/routes/+page.svelte
  src/routes/Resources_Availability_Form/+page.svelte
  src/routes/alert_system/+page.js
  src/routes/alert_system/+page.svelte
  src/routes/fire_and_emergency_page/+page.svelte
  src/routes/rss/+page.svelte
  src/routes/seismic_reports_page/+page.svelte
  src/routes/volcanic_activity_page/+page.svelte
  src/routes/weather_reports_page/+page.svelte
Labels: Sprint

#77 Seismic layout
  src/routes/seismic_reports_page/+page.svelte
Labels: Frontend

#93 Updated Coding Standards
  Coding Standards.md
Labels: documentation
